Update in yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -40,7 +40,18 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            docker pull ${{ secrets.DOCKER_USERNAME }}/heart-stroke:latest
-            docker stop heart-stroke || true
-            docker rm heart-stroke || true
-            docker run -d -p 80:8000 --name heart-stroke ${{ secrets.DOCKER_USERNAME }}/heart-stroke:latest
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              sudo yum update -y
+              sudo yum install -y docker
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            fi
+
+            sudo docker --version
+
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/heart-stroke:latest
+            sudo docker stop heart-stroke || true
+            sudo docker rm heart-stroke || true
+            sudo docker run -d -p 80:8000 --name heart-stroke ${{ secrets.DOCKER_USERNAME }}/heart-stroke:latest
